# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
pin_all_from "app/javascript/controllers", under: "controllers"
pin "@tiptap/core", to: "https://ga.jspm.io/npm:@tiptap/core@2.0.1/dist/index.js"
pin "@tiptap/pm/commands", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/commands/dist/index.js"
pin "@tiptap/pm/keymap", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/keymap/dist/index.js"
pin "@tiptap/pm/model", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/model/dist/index.js"
pin "@tiptap/pm/schema-list", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/schema-list/dist/index.js"
pin "@tiptap/pm/state", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/state/dist/index.js"
pin "@tiptap/pm/transform", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/transform/dist/index.js"
pin "@tiptap/pm/view", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/view/dist/index.js"
pin "orderedmap", to: "https://ga.jspm.io/npm:orderedmap@2.1.0/dist/index.js"
pin "prosemirror-commands", to: "https://ga.jspm.io/npm:prosemirror-commands@1.5.1/dist/index.js"
pin "prosemirror-keymap", to: "https://ga.jspm.io/npm:prosemirror-keymap@1.2.1/dist/index.js"
pin "prosemirror-model", to: "https://ga.jspm.io/npm:prosemirror-model@1.19.0/dist/index.js"
pin "prosemirror-schema-list", to: "https://ga.jspm.io/npm:prosemirror-schema-list@1.2.2/dist/index.js"
pin "prosemirror-state", to: "https://ga.jspm.io/npm:prosemirror-state@1.4.2/dist/index.js"
pin "prosemirror-transform", to: "https://ga.jspm.io/npm:prosemirror-transform@1.7.1/dist/index.js"
pin "prosemirror-view", to: "https://ga.jspm.io/npm:prosemirror-view@1.30.2/dist/index.js"
pin "w3c-keyname", to: "https://ga.jspm.io/npm:w3c-keyname@2.2.6/index.es.js"
pin "@tiptap/starter-kit", to: "https://ga.jspm.io/npm:@tiptap/starter-kit@2.0.1/dist/index.js"
pin "@tiptap/extension-blockquote", to: "https://ga.jspm.io/npm:@tiptap/extension-blockquote@2.0.1/dist/index.js"
pin "@tiptap/extension-bold", to: "https://ga.jspm.io/npm:@tiptap/extension-bold@2.0.1/dist/index.js"
pin "@tiptap/extension-bullet-list", to: "https://ga.jspm.io/npm:@tiptap/extension-bullet-list@2.0.1/dist/index.js"
pin "@tiptap/extension-code", to: "https://ga.jspm.io/npm:@tiptap/extension-code@2.0.1/dist/index.js"
pin "@tiptap/extension-code-block", to: "https://ga.jspm.io/npm:@tiptap/extension-code-block@2.0.1/dist/index.js"
pin "@tiptap/extension-document", to: "https://ga.jspm.io/npm:@tiptap/extension-document@2.0.1/dist/index.js"
pin "@tiptap/extension-dropcursor", to: "https://ga.jspm.io/npm:@tiptap/extension-dropcursor@2.0.1/dist/index.js"
pin "@tiptap/extension-gapcursor", to: "https://ga.jspm.io/npm:@tiptap/extension-gapcursor@2.0.1/dist/index.js"
pin "@tiptap/extension-hard-break", to: "https://ga.jspm.io/npm:@tiptap/extension-hard-break@2.0.1/dist/index.js"
pin "@tiptap/extension-heading", to: "https://ga.jspm.io/npm:@tiptap/extension-heading@2.0.1/dist/index.js"
pin "@tiptap/extension-history", to: "https://ga.jspm.io/npm:@tiptap/extension-history@2.0.1/dist/index.js"
pin "@tiptap/extension-horizontal-rule", to: "https://ga.jspm.io/npm:@tiptap/extension-horizontal-rule@2.0.1/dist/index.js"
pin "@tiptap/extension-italic", to: "https://ga.jspm.io/npm:@tiptap/extension-italic@2.0.1/dist/index.js"
pin "@tiptap/extension-list-item", to: "https://ga.jspm.io/npm:@tiptap/extension-list-item@2.0.1/dist/index.js"
pin "@tiptap/extension-ordered-list", to: "https://ga.jspm.io/npm:@tiptap/extension-ordered-list@2.0.1/dist/index.js"
pin "@tiptap/extension-paragraph", to: "https://ga.jspm.io/npm:@tiptap/extension-paragraph@2.0.1/dist/index.js"
pin "@tiptap/extension-strike", to: "https://ga.jspm.io/npm:@tiptap/extension-strike@2.0.1/dist/index.js"
pin "@tiptap/extension-text", to: "https://ga.jspm.io/npm:@tiptap/extension-text@2.0.1/dist/index.js"
pin "@tiptap/pm/dropcursor", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/dropcursor/dist/index.js"
pin "@tiptap/pm/gapcursor", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/gapcursor/dist/index.js"
pin "@tiptap/pm/history", to: "https://ga.jspm.io/npm:@tiptap/pm@2.0.1/history/dist/index.js"
pin "prosemirror-dropcursor", to: "https://ga.jspm.io/npm:prosemirror-dropcursor@1.8.0/dist/index.js"
pin "prosemirror-gapcursor", to: "https://ga.jspm.io/npm:prosemirror-gapcursor@1.3.1/dist/index.js"
pin "prosemirror-history", to: "https://ga.jspm.io/npm:prosemirror-history@1.3.0/dist/index.js"
pin "rope-sequence", to: "https://ga.jspm.io/npm:rope-sequence@1.3.3/dist/index.es.js"
pin "@tiptap/extension-link", to: "https://ga.jspm.io/npm:@tiptap/extension-link@2.0.1/dist/index.js"
pin "linkifyjs", to: "https://ga.jspm.io/npm:linkifyjs@4.1.1/dist/linkify.es.js"
pin "@tiptap/extension-underline", to: "https://ga.jspm.io/npm:@tiptap/extension-underline@2.0.1/dist/index.js"
